### ISSUE TITLE
 Inconsistent Order of Cost Ratio in README

### ISSUE THREAD

**Issue by es94129** [ray-project/llm-numbers#10]
There is a minor inconsistency of README for "6: Cost Ratio of OpenAI base vs fine tuned model queries", which should be "6: Cost Ratio of fine-tuned model queries vs OpenAI base model queries" (basically switching the two options) so that it's consistent with other usages of "X: Cost Ratio of A vs B" in the README.

Switching the orders of that subtitle would increase clarity and also align with https://en.wikipedia.org/wiki/Ratio.

**Comment by waleedkadous** [comment]
Fixed in #12
