### ISSUE TITLE
Fine tune cost numbers

### ISSUE THREAD

**Issue by smy20011** [ray-project/llm-numbers#2]
> It costs you 6 times as much to serve a fine tuned model as it does the base model on OpenAI.

Do you have any data about it? Is it because the training cost?

**Comment by waleedkadous** [comment]
From the OpenAI prices: 

<img width="1491" alt="image" src="https://github.com/ray-project/llm-numbers/assets/2716496/cc414d80-156c-4b15-afaf-0aa55971127b">

See how Davinci is $0.02/ktoken for instruct GPT but $0.12/ktoken? 0.12/0.02 = 6.

**Comment by smy20011** [comment]
Got it. I thought It's for open source LLMs.
