### ISSUE TITLE
50

### ISSUE THREAD

**Issue by bdytx5** [ray-project/llm-numbers#4]
~50: Cost Ratio of GPT-4 to GPT-3.5 Turbo[3](https://github.com/ray-project/llm-numbers#user-content-fn-3-040af839e3b0c56c68f1ba62559d132e)
What this means is that for many practical applications, it’s much better to use GPT-4 for things like generation and then use that data to fine tune a smaller model. It is roughly 50 times cheaper to use GPT-3.5-Turbo than GPT-4 (the “roughly” is because GPT-4 charges differently for the prompt and the generated output) – so you really need to check on how far you can get with GPT-3.5-Turbo. GPT-3.5-Turbo is more than enough for tasks like summarization for example.

This is a little confusing. How do you come up with 50?

**Comment by waleedkadous** [comment]
It's an approximation of (12c/1k token generated 6c/1k token generated) vs 0.2c / 1k token for GPT-3.5. The prices aren't directly comparable, but they're somewhere around 30x-60x.

**Comment by bdytx5** [comment]
Ok thanks! Cool if i publish an article about this on weights and biases?

**Comment by waleedkadous** [comment]
Absolutely fine! Please point people at this repo so they always get the most up-to-date version.
